library(tidyverse)
murders <- read_csv("data/murders.csv")
murders <- murders %>% mutate(region = factor(region), rate = total/population*10^5)
save(murders, file = "rda/murders.rda")


# save a plot generated by ggplot2 to a dir called "figs"
ggsave("figs/barplot.png")

getwd() # to confirm current working directory

